export const ingredients = [
  {
    _id: "60666c42cc7b410027a1a9b1",
    name: "Краторная булка N-200i",
    name_en: "Crater Bun N-200i",
    type: "bun",
    proteins: 80,
    fat: 24,
    carbohydrates: 53,
    calories: 420,
    price: 1255,
    image: "images/bun-02.png",
    image_mobile: "images/bun-02-mobile.png",
    image_large: "images/bun-02-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9b5",
    name: "Говяжий метеорит (отбивная)",
    name_en: "Meteorite Beef Patty",
    type: "main",
    proteins: 800,
    fat: 800,
    carbohydrates: 300,
    calories: 2674,
    price: 3000,
    image: "images/meat-04.png",
    image_mobile: "images/meat-04-mobile.png",
    image_large: "images/meat-04-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9b6",
    name: "Биокотлета из марсианской Магнолии",
    name_en: "Biopatty from Martian Magnolia",
    type: "main",
    proteins: 420,
    fat: 142,
    carbohydrates: 242,
    calories: 4242,
    price: 424,
    image: "images/meat-01.png",
    image_mobile: "images/meat-01-mobile.png",
    image_large: "images/meat-01-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9b7",
    name: "Соус Spicy-X",
    name_en: "Spicy-X Sauce",
    type: "sauce",
    proteins: 30,
    fat: 20,
    carbohydrates: 40,
    calories: 30,
    price: 90,
    image: "images/sauce-02.png",
    image_mobile: "images/sauce-02-mobile.png",
    image_large: "images/sauce-02-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9b4",
    name: "Мясо бессмертных моллюсков Protostomia",
    name_en: "Immortal Mollusk Meat Protostomia",
    type: "main",
    proteins: 433,
    fat: 244,
    carbohydrates: 33,
    calories: 420,
    price: 1337,
    image: "images/meat-02.png",
    image_mobile: "images/meat-02-mobile.png",
    image_large: "images/meat-02-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9b9",
    name: "Соус традиционный галактический",
    name_en: "Traditional Galactic Sauce",
    type: "sauce",
    proteins: 42,
    fat: 24,
    carbohydrates: 42,
    calories: 99,
    price: 15,
    image: "images/sauce-03.png",
    image_mobile: "images/sauce-03-mobile.png",
    image_large: "images/sauce-03-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9b8",
    name: "Соус фирменный Space Sauce",
    name_en: "Signature Space Sauce",
    type: "sauce",
    proteins: 50,
    fat: 22,
    carbohydrates: 11,
    calories: 14,
    price: 80,
    image: "images/sauce-04.png",
    image_mobile: "images/sauce-04-mobile.png",
    image_large: "images/sauce-04-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9bc",
    name: "Плоды Фалленианского дерева",
    name_en: "Fruits of the Fallenian Tree",
    type: "main",
    proteins: 20,
    fat: 5,
    carbohydrates: 55,
    calories: 77,
    price: 874,
    image: "images/sp_1.png",
    image_mobile: "images/sp_1-mobile.png",
    image_large: "images/sp_1-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9bb",
    name: "Хрустящие минеральные кольца",
    name_en: "Crunchy Mineral Rings",
    type: "main",
    proteins: 808,
    fat: 689,
    carbohydrates: 609,
    calories: 986,
    price: 300,
    image: "images/mineral_rings.png",
    image_mobile: "images/mineral_rings-mobile.png",
    image_large: "images/mineral_rings-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9ba",
    name: "Соус с шипами Антарианского плоскоходца",
    name_en: "Antarian Flatcrawler Thorn Sauce",
    type: "sauce",
    proteins: 101,
    fat: 99,
    carbohydrates: 100,
    calories: 100,
    price: 88,
    image: "images/sauce-01.png",
    image_mobile: "images/sauce-01-mobile.png",
    image_large: "images/sauce-01-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9bd",
    name: "Кристаллы марсианских альфа-сахаридов",
    name_en: "Martian Alpha-Sugar Crystals",
    type: "main",
    proteins: 234,
    fat: 432,
    carbohydrates: 111,
    calories: 189,
    price: 762,
    image: "images/core.png",
    image_mobile: "images/core-mobile.png",
    image_large: "images/core-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9be",
    name: "Мини-салат Экзо-Плантаго",
    name_en: "Mini-Salad Exo-Plantago",
    type: "main",
    proteins: 1,
    fat: 2,
    carbohydrates: 3,
    calories: 6,
    price: 4400,
    image: "images/salad.png",
    image_mobile: "images/salad-mobile.png",
    image_large: "images/salad-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9b3",
    name: "Филе Люминесцентного тетраодонтимформа",
    name_en: "Fillet of Luminescent Tetraodontiform",
    type: "main",
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    image: "images/meat-03.png",
    image_mobile: "images/meat-03-mobile.png",
    image_large: "images/meat-03-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9bf",
    name: "Сыр с астероидной плесенью",
    name_en: "Asteroid Mold Cheese",
    type: "main",
    proteins: 84,
    fat: 48,
    carbohydrates: 420,
    calories: 3377,
    price: 4142,
    image: "images/cheese.png",
    image_mobile: "images/cheese-mobile.png",
    image_large: "images/cheese-large.png",
    __v: 0
  },
  {
    _id: "60666c42cc7b410027a1a9b2",
    name: "Флюоресцентная булка R2-D3",
    name_en: "Fluorescent Bun R2-D3",
    type: "bun",
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    image: "images/bun-01.png",
    image_mobile: "images/bun-01-mobile.png",
    image_large: "images/bun-01-large.png",
    __v: 0
  }
]